# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view\GUI_twingo.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_fm_max_f = QtWidgets.QLabel(self.centralwidget)
        self.label_fm_max_f.setObjectName("label_fm_max_f")
        self.gridLayout.addWidget(self.label_fm_max_f, 2, 2, 1, 1)
        self.comboBox_out_sig_type = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_out_sig_type.setObjectName("comboBox_out_sig_type")
        self.comboBox_out_sig_type.addItem("")
        self.comboBox_out_sig_type.addItem("")
        self.comboBox_out_sig_type.addItem("")
        self.comboBox_out_sig_type.addItem("")
        self.comboBox_out_sig_type.addItem("")
        self.comboBox_out_sig_type.addItem("")
        self.comboBox_out_sig_type.addItem("")
        self.gridLayout.addWidget(self.comboBox_out_sig_type, 1, 1, 1, 1)
        self.lineEdit_max_f = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_max_f.sizePolicy().hasHeightForWidth())
        self.lineEdit_max_f.setSizePolicy(sizePolicy)
        self.lineEdit_max_f.setText("")
        self.lineEdit_max_f.setObjectName("lineEdit_max_f")
        self.gridLayout.addWidget(self.lineEdit_max_f, 2, 3, 1, 1)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout.addWidget(self.pushButton_stop, 2, 5, 1, 1)
        self.label_min_f = QtWidgets.QLabel(self.centralwidget)
        self.label_min_f.setObjectName("label_min_f")
        self.gridLayout.addWidget(self.label_min_f, 1, 2, 1, 1)
        self.lineEdit_min_f = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_min_f.sizePolicy().hasHeightForWidth())
        self.lineEdit_min_f.setSizePolicy(sizePolicy)
        self.lineEdit_min_f.setText("")
        self.lineEdit_min_f.setObjectName("lineEdit_min_f")
        self.gridLayout.addWidget(self.lineEdit_min_f, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.comboBox_sig_len = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_sig_len.setEditable(False)
        self.comboBox_sig_len.setObjectName("comboBox_sig_len")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.comboBox_sig_len.addItem("")
        self.gridLayout.addWidget(self.comboBox_sig_len, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(5, 112, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(5, 112, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(5, 112, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_start.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setAutoFillBackground(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 1, 5, 1, 1)
        self.buffer_indicator_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.buffer_indicator_label.setFont(font)
        self.buffer_indicator_label.setText("")
        self.buffer_indicator_label.setObjectName("buffer_indicator_label")
        self.gridLayout.addWidget(self.buffer_indicator_label, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(65, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 4, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_main.sizePolicy().hasHeightForWidth())
        self.tabWidget_main.setSizePolicy(sizePolicy)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_settings)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_detectDAQ = QtWidgets.QPushButton(self.tab_settings)
        self.pushButton_detectDAQ.setObjectName("pushButton_detectDAQ")
        self.horizontalLayout.addWidget(self.pushButton_detectDAQ)
        self.comboBox_dev_list = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_dev_list.setStatusTip("")
        self.comboBox_dev_list.setFrame(True)
        self.comboBox_dev_list.setObjectName("comboBox_dev_list")
        self.horizontalLayout.addWidget(self.comboBox_dev_list)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.tab_settings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.label_4 = QtWidgets.QLabel(self.tab_settings)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_ai_a = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ai_a.setObjectName("comboBox_ai_a")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_ai_a)
        self.label_3 = QtWidgets.QLabel(self.tab_settings)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_ai_b = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ai_b.setObjectName("comboBox_ai_b")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_ai_b)
        self.label_5 = QtWidgets.QLabel(self.tab_settings)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_ai_terminal_cfg = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ai_terminal_cfg.setObjectName("comboBox_ai_terminal_cfg")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_ai_terminal_cfg)
        self.label = QtWidgets.QLabel(self.tab_settings)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_ai_max = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ai_max.setObjectName("comboBox_ai_max")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_ai_max)
        self.label_2 = QtWidgets.QLabel(self.tab_settings)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_ai_min = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ai_min.setObjectName("comboBox_ai_min")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_ai_min)
        self.label_6 = QtWidgets.QLabel(self.tab_settings)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_ai_fs = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ai_fs.setObjectName("comboBox_ai_fs")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_ai_fs)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(self.tab_settings)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.tab_settings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.tab_settings)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBox_ao_a = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ao_a.setObjectName("comboBox_ao_a")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_ao_a)
        self.label_10 = QtWidgets.QLabel(self.tab_settings)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboBox_ao_b = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ao_b.setObjectName("comboBox_ao_b")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_ao_b)
        self.Label = QtWidgets.QLabel(self.tab_settings)
        self.Label.setEnabled(False)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.Label.setFont(font)
        self.Label.setObjectName("Label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.comboBox = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_11 = QtWidgets.QLabel(self.tab_settings)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBox_ao_max = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ao_max.setObjectName("comboBox_ao_max")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_ao_max)
        self.label_12 = QtWidgets.QLabel(self.tab_settings)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.comboBox_ao_min = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ao_min.setObjectName("comboBox_ao_min")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_ao_min)
        self.label_13 = QtWidgets.QLabel(self.tab_settings)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_ao_fs = QtWidgets.QComboBox(self.tab_settings)
        self.comboBox_ao_fs.setObjectName("comboBox_ao_fs")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_ao_fs)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_settings, "")
        self.tab_cm = QtWidgets.QWidget()
        self.tab_cm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.tab_cm.setFont(font)
        self.tab_cm.setObjectName("tab_cm")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_cm)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab_cm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setProperty("value", 1000.0)
        self.lcdNumber.setProperty("intValue", 1000)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.dial_cm_vfine_freq = QtWidgets.QDial(self.groupBox)
        self.dial_cm_vfine_freq.setMinimum(1)
        self.dial_cm_vfine_freq.setMaximum(100)
        self.dial_cm_vfine_freq.setPageStep(10)
        self.dial_cm_vfine_freq.setProperty("value", 50)
        self.dial_cm_vfine_freq.setWrapping(False)
        self.dial_cm_vfine_freq.setNotchTarget(2.0)
        self.dial_cm_vfine_freq.setNotchesVisible(True)
        self.dial_cm_vfine_freq.setObjectName("dial_cm_vfine_freq")
        self.verticalLayout.addWidget(self.dial_cm_vfine_freq)
        self.dial_cm_fine_freq = QtWidgets.QDial(self.groupBox)
        self.dial_cm_fine_freq.setMinimum(0)
        self.dial_cm_fine_freq.setMaximum(1000)
        self.dial_cm_fine_freq.setSingleStep(10)
        self.dial_cm_fine_freq.setPageStep(100)
        self.dial_cm_fine_freq.setProperty("value", 500)
        self.dial_cm_fine_freq.setTracking(True)
        self.dial_cm_fine_freq.setWrapping(False)
        self.dial_cm_fine_freq.setNotchTarget(5.0)
        self.dial_cm_fine_freq.setNotchesVisible(True)
        self.dial_cm_fine_freq.setObjectName("dial_cm_fine_freq")
        self.verticalLayout.addWidget(self.dial_cm_fine_freq)
        self.dial_cm_coarse_freq = QtWidgets.QDial(self.groupBox)
        self.dial_cm_coarse_freq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dial_cm_coarse_freq.setAutoFillBackground(False)
        self.dial_cm_coarse_freq.setMinimum(0)
        self.dial_cm_coarse_freq.setMaximum(20000)
        self.dial_cm_coarse_freq.setSingleStep(100)
        self.dial_cm_coarse_freq.setPageStep(1000)
        self.dial_cm_coarse_freq.setProperty("value", 1000)
        self.dial_cm_coarse_freq.setTracking(True)
        self.dial_cm_coarse_freq.setInvertedAppearance(False)
        self.dial_cm_coarse_freq.setWrapping(False)
        self.dial_cm_coarse_freq.setNotchTarget(1.0)
        self.dial_cm_coarse_freq.setNotchesVisible(True)
        self.dial_cm_coarse_freq.setObjectName("dial_cm_coarse_freq")
        self.verticalLayout.addWidget(self.dial_cm_coarse_freq)
        self.gridLayout_7.addWidget(self.groupBox, 0, 1, 1, 1)
        self.tabWidget_cm = QtWidgets.QTabWidget(self.tab_cm)
        self.tabWidget_cm.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_cm.sizePolicy().hasHeightForWidth())
        self.tabWidget_cm.setSizePolicy(sizePolicy)
        self.tabWidget_cm.setObjectName("tabWidget_cm")
        self.tab_cm_timeseries = QtWidgets.QWidget()
        self.tab_cm_timeseries.setObjectName("tab_cm_timeseries")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_cm_timeseries)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.cm_tm_verticalLayout = QtWidgets.QVBoxLayout()
        self.cm_tm_verticalLayout.setObjectName("cm_tm_verticalLayout")
        self.gridLayout_10.addLayout(self.cm_tm_verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_26 = QtWidgets.QLabel(self.tab_cm_timeseries)
        self.label_26.setEnabled(False)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_6.addWidget(self.label_26)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.checkBox_cm_tm_hold_a = QtWidgets.QCheckBox(self.tab_cm_timeseries)
        self.checkBox_cm_tm_hold_a.setEnabled(True)
        self.checkBox_cm_tm_hold_a.setObjectName("checkBox_cm_tm_hold_a")
        self.horizontalLayout_6.addWidget(self.checkBox_cm_tm_hold_a)
        self.checkBox_cm_tm_hold_b = QtWidgets.QCheckBox(self.tab_cm_timeseries)
        self.checkBox_cm_tm_hold_b.setEnabled(True)
        self.checkBox_cm_tm_hold_b.setObjectName("checkBox_cm_tm_hold_b")
        self.horizontalLayout_6.addWidget(self.checkBox_cm_tm_hold_b)
        self.gridLayout_10.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.tabWidget_cm.addTab(self.tab_cm_timeseries, "")
        self.tab_cm_spectrum = QtWidgets.QWidget()
        self.tab_cm_spectrum.setObjectName("tab_cm_spectrum")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_cm_spectrum)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.cm_sp_verticalLayout = QtWidgets.QVBoxLayout()
        self.cm_sp_verticalLayout.setObjectName("cm_sp_verticalLayout")
        self.gridLayout_11.addLayout(self.cm_sp_verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_21 = QtWidgets.QLabel(self.tab_cm_spectrum)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_7.addWidget(self.label_21)
        self.comboBox_cm_window_type = QtWidgets.QComboBox(self.tab_cm_spectrum)
        self.comboBox_cm_window_type.setObjectName("comboBox_cm_window_type")
        self.comboBox_cm_window_type.addItem("")
        self.comboBox_cm_window_type.addItem("")
        self.comboBox_cm_window_type.addItem("")
        self.comboBox_cm_window_type.addItem("")
        self.comboBox_cm_window_type.addItem("")
        self.comboBox_cm_window_type.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_cm_window_type)
        self.label_22 = QtWidgets.QLabel(self.tab_cm_spectrum)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_7.addWidget(self.label_22)
        self.comboBox_cm_window_size = QtWidgets.QComboBox(self.tab_cm_spectrum)
        self.comboBox_cm_window_size.setCurrentText("")
        self.comboBox_cm_window_size.setObjectName("comboBox_cm_window_size")
        self.horizontalLayout_7.addWidget(self.comboBox_cm_window_size)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.label_27 = QtWidgets.QLabel(self.tab_cm_spectrum)
        self.label_27.setEnabled(False)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_7.addWidget(self.label_27)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.checkBox_cm_sp_hold_a = QtWidgets.QCheckBox(self.tab_cm_spectrum)
        self.checkBox_cm_sp_hold_a.setEnabled(True)
        self.checkBox_cm_sp_hold_a.setObjectName("checkBox_cm_sp_hold_a")
        self.horizontalLayout_7.addWidget(self.checkBox_cm_sp_hold_a)
        self.checkBox_cm_sp_hold_b = QtWidgets.QCheckBox(self.tab_cm_spectrum)
        self.checkBox_cm_sp_hold_b.setEnabled(True)
        self.checkBox_cm_sp_hold_b.setObjectName("checkBox_cm_sp_hold_b")
        self.horizontalLayout_7.addWidget(self.checkBox_cm_sp_hold_b)
        self.gridLayout_11.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.tabWidget_cm.addTab(self.tab_cm_spectrum, "")
        self.tab_cm_phase = QtWidgets.QWidget()
        self.tab_cm_phase.setObjectName("tab_cm_phase")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_cm_phase)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.cm_ph_horizontalLayout = QtWidgets.QHBoxLayout()
        self.cm_ph_horizontalLayout.setObjectName("cm_ph_horizontalLayout")
        self.gridLayout_9.addLayout(self.cm_ph_horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.label_28 = QtWidgets.QLabel(self.tab_cm_phase)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_8.addWidget(self.label_28)
        self.comboBox_cm_ph_window_size = QtWidgets.QComboBox(self.tab_cm_phase)
        self.comboBox_cm_ph_window_size.setObjectName("comboBox_cm_ph_window_size")
        self.horizontalLayout_8.addWidget(self.comboBox_cm_ph_window_size)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.label_29 = QtWidgets.QLabel(self.tab_cm_phase)
        self.label_29.setEnabled(False)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_8.addWidget(self.label_29)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.checkBox_cm_ph_hold_1 = QtWidgets.QCheckBox(self.tab_cm_phase)
        self.checkBox_cm_ph_hold_1.setObjectName("checkBox_cm_ph_hold_1")
        self.horizontalLayout_8.addWidget(self.checkBox_cm_ph_hold_1)
        self.checkBox_cm_ph_hold_2 = QtWidgets.QCheckBox(self.tab_cm_phase)
        self.checkBox_cm_ph_hold_2.setObjectName("checkBox_cm_ph_hold_2")
        self.horizontalLayout_8.addWidget(self.checkBox_cm_ph_hold_2)
        self.gridLayout_9.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.tabWidget_cm.addTab(self.tab_cm_phase, "")
        self.gridLayout_7.addWidget(self.tabWidget_cm, 0, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_cm, "")
        self.tab_fm = QtWidgets.QWidget()
        self.tab_fm.setObjectName("tab_fm")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_fm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_fm = QtWidgets.QTabWidget(self.tab_fm)
        self.tabWidget_fm.setObjectName("tabWidget_fm")
        self.tab_timeseries = QtWidgets.QWidget()
        self.tab_timeseries.setObjectName("tab_timeseries")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_timeseries)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tm_verticalLayout = QtWidgets.QVBoxLayout()
        self.tm_verticalLayout.setObjectName("tm_verticalLayout")
        self.gridLayout_5.addLayout(self.tm_verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.label_23 = QtWidgets.QLabel(self.tab_timeseries)
        self.label_23.setEnabled(False)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.checkBox_fm_tm_hold_a = QtWidgets.QCheckBox(self.tab_timeseries)
        self.checkBox_fm_tm_hold_a.setEnabled(True)
        self.checkBox_fm_tm_hold_a.setObjectName("checkBox_fm_tm_hold_a")
        self.horizontalLayout_4.addWidget(self.checkBox_fm_tm_hold_a)
        self.checkBox_fm_tm_hold_b = QtWidgets.QCheckBox(self.tab_timeseries)
        self.checkBox_fm_tm_hold_b.setEnabled(True)
        self.checkBox_fm_tm_hold_b.setObjectName("checkBox_fm_tm_hold_b")
        self.horizontalLayout_4.addWidget(self.checkBox_fm_tm_hold_b)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.tabWidget_fm.addTab(self.tab_timeseries, "")
        self.tab_spectrum = QtWidgets.QWidget()
        self.tab_spectrum.setObjectName("tab_spectrum")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_spectrum)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sp_verticalLayout = QtWidgets.QVBoxLayout()
        self.sp_verticalLayout.setObjectName("sp_verticalLayout")
        self.gridLayout_6.addLayout(self.sp_verticalLayout, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_19 = QtWidgets.QLabel(self.tab_spectrum)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.comboBox_fm_window_type = QtWidgets.QComboBox(self.tab_spectrum)
        self.comboBox_fm_window_type.setMinimumSize(QtCore.QSize(117, 0))
        self.comboBox_fm_window_type.setObjectName("comboBox_fm_window_type")
        self.comboBox_fm_window_type.addItem("")
        self.comboBox_fm_window_type.addItem("")
        self.comboBox_fm_window_type.addItem("")
        self.comboBox_fm_window_type.addItem("")
        self.comboBox_fm_window_type.addItem("")
        self.comboBox_fm_window_type.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_fm_window_type)
        self.label_20 = QtWidgets.QLabel(self.tab_spectrum)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        self.comboBox_fm_window_size = QtWidgets.QComboBox(self.tab_spectrum)
        self.comboBox_fm_window_size.setObjectName("comboBox_fm_window_size")
        self.horizontalLayout_3.addWidget(self.comboBox_fm_window_size)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.label_24 = QtWidgets.QLabel(self.tab_spectrum)
        self.label_24.setEnabled(False)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_3.addWidget(self.label_24)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.checkBox_fm_sp_hold_a = QtWidgets.QCheckBox(self.tab_spectrum)
        self.checkBox_fm_sp_hold_a.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_fm_sp_hold_a.setFont(font)
        self.checkBox_fm_sp_hold_a.setAutoFillBackground(False)
        self.checkBox_fm_sp_hold_a.setObjectName("checkBox_fm_sp_hold_a")
        self.horizontalLayout_3.addWidget(self.checkBox_fm_sp_hold_a)
        self.checkBox_fm_sp_hold_b = QtWidgets.QCheckBox(self.tab_spectrum)
        self.checkBox_fm_sp_hold_b.setEnabled(True)
        self.checkBox_fm_sp_hold_b.setObjectName("checkBox_fm_sp_hold_b")
        self.horizontalLayout_3.addWidget(self.checkBox_fm_sp_hold_b)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.tabWidget_fm.addTab(self.tab_spectrum, "")
        self.tab_spg = QtWidgets.QWidget()
        self.tab_spg.setObjectName("tab_spg")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_spg)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.spg_verticalLayout = QtWidgets.QVBoxLayout()
        self.spg_verticalLayout.setObjectName("spg_verticalLayout")
        self.gridLayout_8.addLayout(self.spg_verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.tab_spg)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.comboBox_fm_spg_window_type = QtWidgets.QComboBox(self.tab_spg)
        self.comboBox_fm_spg_window_type.setObjectName("comboBox_fm_spg_window_type")
        self.comboBox_fm_spg_window_type.addItem("")
        self.comboBox_fm_spg_window_type.addItem("")
        self.comboBox_fm_spg_window_type.addItem("")
        self.comboBox_fm_spg_window_type.addItem("")
        self.comboBox_fm_spg_window_type.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_fm_spg_window_type)
        self.label_16 = QtWidgets.QLabel(self.tab_spg)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.comboBox_fm_spg_window_size = QtWidgets.QComboBox(self.tab_spg)
        self.comboBox_fm_spg_window_size.setObjectName("comboBox_fm_spg_window_size")
        self.horizontalLayout_5.addWidget(self.comboBox_fm_spg_window_size)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.label_25 = QtWidgets.QLabel(self.tab_spg)
        self.label_25.setEnabled(False)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.label_18 = QtWidgets.QLabel(self.tab_spg)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_5.addWidget(self.label_18)
        self.comboBox_fm_spg_chan = QtWidgets.QComboBox(self.tab_spg)
        self.comboBox_fm_spg_chan.setObjectName("comboBox_fm_spg_chan")
        self.comboBox_fm_spg_chan.addItem("")
        self.comboBox_fm_spg_chan.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_fm_spg_chan)
        self.checkBox_fm_spg_log_amp = QtWidgets.QCheckBox(self.tab_spg)
        self.checkBox_fm_spg_log_amp.setChecked(True)
        self.checkBox_fm_spg_log_amp.setObjectName("checkBox_fm_spg_log_amp")
        self.horizontalLayout_5.addWidget(self.checkBox_fm_spg_log_amp)
        self.checkBox_fm_log_f = QtWidgets.QCheckBox(self.tab_spg)
        self.checkBox_fm_log_f.setEnabled(False)
        self.checkBox_fm_log_f.setObjectName("checkBox_fm_log_f")
        self.horizontalLayout_5.addWidget(self.checkBox_fm_log_f)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.tabWidget_fm.addTab(self.tab_spg, "")
        self.gridLayout_2.addWidget(self.tabWidget_fm, 1, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_fm, "")
        self.gridLayout_3.addWidget(self.tabWidget_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 26))
        self.menubar.setObjectName("menubar")
        self.menuHW_config = QtWidgets.QMenu(self.menubar)
        self.menuHW_config.setObjectName("menuHW_config")
        MainWindow.setMenuBar(self.menubar)
        self.menuHW_config.addSeparator()
        self.menubar.addAction(self.menuHW_config.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_sig_len.setCurrentIndex(2)
        self.tabWidget_main.setCurrentIndex(1)
        self.tabWidget_cm.setCurrentIndex(2)
        self.comboBox_cm_window_size.setCurrentIndex(-1)
        self.tabWidget_fm.setCurrentIndex(2)
        self.comboBox_fm_window_size.setCurrentIndex(-1)
        self.comboBox_fm_spg_window_type.setCurrentIndex(0)
        self.comboBox_fm_spg_window_size.setCurrentIndex(-1)
        self.comboBox_ai_a.currentIndexChanged['int'].connect(self.comboBox_ai_b.setCurrentIndex)
        self.comboBox_ai_b.currentIndexChanged['int'].connect(self.comboBox_ai_a.setCurrentIndex)
        self.comboBox_ao_a.currentIndexChanged['int'].connect(self.comboBox_ao_b.setCurrentIndex)
        self.comboBox_ao_b.currentIndexChanged['int'].connect(self.comboBox_ao_a.setCurrentIndex)
        self.comboBox_ai_max.currentIndexChanged['int'].connect(self.comboBox_ai_min.setCurrentIndex)
        self.comboBox_ai_min.currentIndexChanged['int'].connect(self.comboBox_ai_max.setCurrentIndex)
        self.comboBox_ao_max.currentIndexChanged['int'].connect(self.comboBox_ao_min.setCurrentIndex)
        self.comboBox_ao_min.currentIndexChanged['int'].connect(self.comboBox_ao_max.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Twingo"))
        self.label_fm_max_f.setText(_translate("MainWindow", "(max/set) f [Hz]:"))
        self.comboBox_out_sig_type.setToolTip(_translate("MainWindow", "select output signal and analysis type"))
        self.comboBox_out_sig_type.setCurrentText(_translate("MainWindow", "sine"))
        self.comboBox_out_sig_type.setItemText(0, _translate("MainWindow", "sine"))
        self.comboBox_out_sig_type.setItemText(1, _translate("MainWindow", "square"))
        self.comboBox_out_sig_type.setItemText(2, _translate("MainWindow", "white noise"))
        self.comboBox_out_sig_type.setItemText(3, _translate("MainWindow", "impulse"))
        self.comboBox_out_sig_type.setItemText(4, _translate("MainWindow", "sweep"))
        self.comboBox_out_sig_type.setItemText(5, _translate("MainWindow", "ess"))
        self.comboBox_out_sig_type.setItemText(6, _translate("MainWindow", "zeros"))
        self.lineEdit_max_f.setToolTip(_translate("MainWindow", "set/end freqency / higher cutoff of the filter"))
        self.pushButton_stop.setToolTip(_translate("MainWindow", "stop continuous measurement"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.label_min_f.setText(_translate("MainWindow", "min f [Hz]:"))
        self.lineEdit_min_f.setToolTip(_translate("MainWindow", "start freqency of the sweeps /lower cutoff of the filter."))
        self.label_14.setText(_translate("MainWindow", "output sig.:"))
        self.comboBox_sig_len.setToolTip(_translate("MainWindow", "finite measurement length"))
        self.comboBox_sig_len.setCurrentText(_translate("MainWindow", "1"))
        self.comboBox_sig_len.setItemText(0, _translate("MainWindow", "0.25"))
        self.comboBox_sig_len.setItemText(1, _translate("MainWindow", "0.5"))
        self.comboBox_sig_len.setItemText(2, _translate("MainWindow", "1"))
        self.comboBox_sig_len.setItemText(3, _translate("MainWindow", "2"))
        self.comboBox_sig_len.setItemText(4, _translate("MainWindow", "3"))
        self.comboBox_sig_len.setItemText(5, _translate("MainWindow", "4"))
        self.comboBox_sig_len.setItemText(6, _translate("MainWindow", "5"))
        self.comboBox_sig_len.setItemText(7, _translate("MainWindow", "6"))
        self.comboBox_sig_len.setItemText(8, _translate("MainWindow", "7"))
        self.comboBox_sig_len.setItemText(9, _translate("MainWindow", "8"))
        self.comboBox_sig_len.setItemText(10, _translate("MainWindow", "9"))
        self.comboBox_sig_len.setItemText(11, _translate("MainWindow", "10"))
        self.comboBox_sig_len.setItemText(12, _translate("MainWindow", "15"))
        self.comboBox_sig_len.setItemText(13, _translate("MainWindow", "20"))
        self.label_15.setText(_translate("MainWindow", "sig length [s]:"))
        self.pushButton_start.setToolTip(_translate("MainWindow", "start measurement"))
        self.pushButton_start.setText(_translate("MainWindow", "START"))
        self.pushButton_detectDAQ.setToolTip(_translate("MainWindow", "detect data acquistion devices"))
        self.pushButton_detectDAQ.setText(_translate("MainWindow", "Detect DAQ"))
        self.comboBox_dev_list.setToolTip(_translate("MainWindow", "Select DAQ device from the list"))
        self.label_7.setText(_translate("MainWindow", "DAQ Input settings"))
        self.label_4.setText(_translate("MainWindow", "Ch.A"))
        self.comboBox_ai_a.setToolTip(_translate("MainWindow", "Select input channel A"))
        self.label_3.setText(_translate("MainWindow", "Ch.B"))
        self.comboBox_ai_b.setToolTip(_translate("MainWindow", "Select input channel B"))
        self.label_5.setText(_translate("MainWindow", "Config"))
        self.comboBox_ai_terminal_cfg.setToolTip(_translate("MainWindow", "Select input configuration"))
        self.label.setText(_translate("MainWindow", "Max limt [V]"))
        self.comboBox_ai_max.setToolTip(_translate("MainWindow", "Select upper input signal limit"))
        self.label_2.setText(_translate("MainWindow", "Min. limit [V]"))
        self.comboBox_ai_min.setToolTip(_translate("MainWindow", "Select lower input signal limit"))
        self.label_6.setText(_translate("MainWindow", "Fs [Hz]"))
        self.label_8.setText(_translate("MainWindow", "DAQ Output settings"))
        self.label_9.setText(_translate("MainWindow", "Ch.A"))
        self.comboBox_ao_a.setToolTip(_translate("MainWindow", "Select first output channel"))
        self.label_10.setText(_translate("MainWindow", "Ch.B"))
        self.comboBox_ao_b.setToolTip(_translate("MainWindow", "Select second output channel"))
        self.Label.setText(_translate("MainWindow", "Config"))
        self.label_11.setText(_translate("MainWindow", "Max limit [V]"))
        self.comboBox_ao_max.setToolTip(_translate("MainWindow", "Set upper ouput signal limit"))
        self.label_12.setText(_translate("MainWindow", "Min limit [V]"))
        self.comboBox_ao_min.setToolTip(_translate("MainWindow", "Set lower output signal limit"))
        self.label_13.setText(_translate("MainWindow", "Fs [Hz]"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_settings), _translate("MainWindow", "Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "(max/set) f [Hz]:"))
        self.dial_cm_vfine_freq.setToolTip(_translate("MainWindow", "freq dial 1Hz -100 Hz"))
        self.dial_cm_fine_freq.setToolTip(_translate("MainWindow", "freq dial 0Hz -1kHz"))
        self.dial_cm_coarse_freq.setToolTip(_translate("MainWindow", "freq dial 0Hz -20kHz"))
        self.label_26.setText(_translate("MainWindow", "Time (<b>s</b>)"))
        self.checkBox_cm_tm_hold_a.setToolTip(_translate("MainWindow", "hold ch. A plot"))
        self.checkBox_cm_tm_hold_a.setText(_translate("MainWindow", "hold A"))
        self.checkBox_cm_tm_hold_b.setToolTip(_translate("MainWindow", "hold ch.B plot"))
        self.checkBox_cm_tm_hold_b.setText(_translate("MainWindow", "hold B"))
        self.tabWidget_cm.setTabText(self.tabWidget_cm.indexOf(self.tab_cm_timeseries), _translate("MainWindow", "timeseries"))
        self.label_21.setText(_translate("MainWindow", "window:"))
        self.comboBox_cm_window_type.setToolTip(_translate("MainWindow", "select fft window type"))
        self.comboBox_cm_window_type.setItemText(0, _translate("MainWindow", "blackmanharris"))
        self.comboBox_cm_window_type.setItemText(1, _translate("MainWindow", "hamming"))
        self.comboBox_cm_window_type.setItemText(2, _translate("MainWindow", "hann"))
        self.comboBox_cm_window_type.setItemText(3, _translate("MainWindow", "blackman"))
        self.comboBox_cm_window_type.setItemText(4, _translate("MainWindow", "boxcar"))
        self.comboBox_cm_window_type.setItemText(5, _translate("MainWindow", "flattop"))
        self.label_22.setText(_translate("MainWindow", "size:"))
        self.comboBox_cm_window_size.setToolTip(_translate("MainWindow", "select fft window length"))
        self.label_27.setText(_translate("MainWindow", "Frequency (<b>Hz</b>)"))
        self.checkBox_cm_sp_hold_a.setToolTip(_translate("MainWindow", "hold ch.A plot"))
        self.checkBox_cm_sp_hold_a.setText(_translate("MainWindow", "hold A"))
        self.checkBox_cm_sp_hold_b.setToolTip(_translate("MainWindow", "hold ch.B plot"))
        self.checkBox_cm_sp_hold_b.setText(_translate("MainWindow", "hold B"))
        self.tabWidget_cm.setTabText(self.tabWidget_cm.indexOf(self.tab_cm_spectrum), _translate("MainWindow", "spectrum"))
        self.label_28.setText(_translate("MainWindow", "size:"))
        self.label_29.setText(_translate("MainWindow", "Stereo Width [-]"))
        self.checkBox_cm_ph_hold_1.setText(_translate("MainWindow", "hold 1"))
        self.checkBox_cm_ph_hold_2.setText(_translate("MainWindow", "hold 2"))
        self.tabWidget_cm.setTabText(self.tabWidget_cm.indexOf(self.tab_cm_phase), _translate("MainWindow", "phase"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_cm), _translate("MainWindow", "Continuous Meas"))
        self.label_23.setText(_translate("MainWindow", "Time (<b>s</b>)"))
        self.checkBox_fm_tm_hold_a.setStatusTip(_translate("MainWindow", "hold ch. A plot"))
        self.checkBox_fm_tm_hold_a.setText(_translate("MainWindow", "hold A"))
        self.checkBox_fm_tm_hold_b.setStatusTip(_translate("MainWindow", "hold ch. B plot"))
        self.checkBox_fm_tm_hold_b.setText(_translate("MainWindow", "hold B"))
        self.tabWidget_fm.setTabText(self.tabWidget_fm.indexOf(self.tab_timeseries), _translate("MainWindow", "timeseries"))
        self.label_19.setText(_translate("MainWindow", "window:"))
        self.comboBox_fm_window_type.setToolTip(_translate("MainWindow", "select fft window type"))
        self.comboBox_fm_window_type.setItemText(0, _translate("MainWindow", "blackmanharris"))
        self.comboBox_fm_window_type.setItemText(1, _translate("MainWindow", "hann"))
        self.comboBox_fm_window_type.setItemText(2, _translate("MainWindow", "hamming"))
        self.comboBox_fm_window_type.setItemText(3, _translate("MainWindow", "blackman"))
        self.comboBox_fm_window_type.setItemText(4, _translate("MainWindow", "boxcar"))
        self.comboBox_fm_window_type.setItemText(5, _translate("MainWindow", "flattop"))
        self.label_20.setText(_translate("MainWindow", "size:"))
        self.comboBox_fm_window_size.setToolTip(_translate("MainWindow", "select fft window length"))
        self.label_24.setText(_translate("MainWindow", "Frequency (<b>Hz</b>)"))
        self.checkBox_fm_sp_hold_a.setStatusTip(_translate("MainWindow", "hold ch. A plot"))
        self.checkBox_fm_sp_hold_a.setText(_translate("MainWindow", "hold A"))
        self.checkBox_fm_sp_hold_b.setStatusTip(_translate("MainWindow", "hold ch. B plot"))
        self.checkBox_fm_sp_hold_b.setText(_translate("MainWindow", "hold B"))
        self.tabWidget_fm.setTabText(self.tabWidget_fm.indexOf(self.tab_spectrum), _translate("MainWindow", "spectrum"))
        self.label_17.setText(_translate("MainWindow", "window:"))
        self.comboBox_fm_spg_window_type.setToolTip(_translate("MainWindow", "select fft window type"))
        self.comboBox_fm_spg_window_type.setItemText(0, _translate("MainWindow", "hann"))
        self.comboBox_fm_spg_window_type.setItemText(1, _translate("MainWindow", "hamming"))
        self.comboBox_fm_spg_window_type.setItemText(2, _translate("MainWindow", "blackman"))
        self.comboBox_fm_spg_window_type.setItemText(3, _translate("MainWindow", "blackmanharris"))
        self.comboBox_fm_spg_window_type.setItemText(4, _translate("MainWindow", "flattop"))
        self.label_16.setText(_translate("MainWindow", "size:"))
        self.comboBox_fm_spg_window_size.setToolTip(_translate("MainWindow", "select fft window length"))
        self.label_25.setText(_translate("MainWindow", "Time (<b>s</b>)"))
        self.label_18.setText(_translate("MainWindow", "chan:"))
        self.comboBox_fm_spg_chan.setToolTip(_translate("MainWindow", "select input chanel for spectrogram"))
        self.comboBox_fm_spg_chan.setItemText(0, _translate("MainWindow", "A"))
        self.comboBox_fm_spg_chan.setItemText(1, _translate("MainWindow", "B"))
        self.checkBox_fm_spg_log_amp.setToolTip(_translate("MainWindow", "set color scale to logarithmic"))
        self.checkBox_fm_spg_log_amp.setText(_translate("MainWindow", "Log(Amp)"))
        self.checkBox_fm_log_f.setText(_translate("MainWindow", "Log(f)"))
        self.tabWidget_fm.setTabText(self.tabWidget_fm.indexOf(self.tab_spg), _translate("MainWindow", "spectrogram"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_fm), _translate("MainWindow", "Finite Meas"))
        self.menuHW_config.setTitle(_translate("MainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
